language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN=b2424da2-b653-442c-82b2-bde6413cb412

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - itismineeee@gmail.com
    on_success: never # default: change
    on_failure: always # default: always